### ISSUE TITLE
Method keys_match() returns different keys types for Redis and memory

### ISSUE THREAD

**Issue by easysugar** [Krukov/cashews#62] opened 2022-05-06 12:35 UTC
Method `keys_match()` returns keys in `bytes` type for Redis cache and in `str` type for memory cache. Is it a bug or feature?

Code example:
```python
# setup two caches - for redis & memory
cache.setup(f'redis://{host}:{port}', password=pwd, prefix='test_redis')
cache.setup('mem://', prefix='test_mem')

# set values for memory and redis
await cache.set('test_redis:abc', 123)
await cache.set('test_mem:abc', 321)

# keys_match result
async def foo(mask):
  async for key in cache.keys_match(mask):
    print(key, type(key))

await foo('test_redis:*')
# b'test_redis:abc' <class 'bytes'>
await foo('test_mem:*')
# test_mem:abc <class 'str'>
```

**Comment by AIGeneratedUsername** [comment] 2022-05-06 16:41
Memory cache is a dictionary with strings as keys. The input key is a string, and it is stored as a string, and returned as a string. It is never converted or stored as bytes. What you are describing is an expected behavior.

**Comment by easysugar** [comment] 2022-05-06 19:01
I think that it's better to expect the same type of keys, no matter what type of cache you are using. Maybe adding a new parameter to `keys_match` can solve the problem? Something like `decode=True` for getting string keys anyway.

P.S.
Type hinting is a good thing anyway. I can try to do it later.

**Comment by AIGeneratedUsername** [comment] 2022-05-06 19:48
> I think that it's better to expect the same type of keys, no matter what type of cache you are using. Maybe adding a new parameter to keys_match can solve the problem? Something like decode=True for getting string keys anyway.

It makes no sense to convert strings to bytes for Memory backend just because Redis returns bytes. I think we can update `keys_match` for the Redis backend to return strings by default or add `decode=True` as you said. 

I will create a pull request when I will have some time and if someone else will not do this sooner.

**Comment by easysugar** [comment] 2022-05-06 20:22
> It makes no sense to convert strings to bytes

Agree.

> to return strings by default

I'm afraid it can lead to unexpected behaviour for someone else who uses this method. Additional parameter should be OK.

**Comment by AIGeneratedUsername** [comment] 2022-05-07 11:06
@Krukov From the project design point of view, I am not sure whether it is required to update the interface 

```python
# cashews/backends/interface.py


class Backend:

    async def keys_match(self, pattern: str, *, decode: bool = False):
        ...
```
because it will be required to pass an unused `decode` parameter to all backends.

Maybe it will be enough to update only a [single place in the code](https://github.com/Krukov/cashews/pull/63/files)?

**Comment by Krukov** [comment] 2022-05-08 17:16
Yep, it is a bug I from my point of view it will be much better to have the same type regardless backend type or even parameter.  And I think if the `pattern` is string the keys is also should be a string ( of course we can have decode error while we try to make string from bites)

@easysugar  I just want to warn that you should avoid use this method in production, because it use `KEYS` method (for redis backend):

> Warning: consider KEYS as a command that should only be used in production environments with extreme care. It may ruin performance when it is executed against large databases.

**Comment by AIGeneratedUsername** [comment] 2022-05-08 17:30
> @easysugar I just want to warn that you should avoid use this method in production, because it use KEYS method (for redis backend):

I do not understand why do you mention the `KEYS` Redis command. If you are talking about the `cashews.backends.redis.backend._Redis.keys_match` defined [here](https://github.com/Krukov/cashews/blob/master/cashews/backends/redis/backend.py#L161), then it uses the [SCAN](https://redis.io/commands/scan/) method, not `KEYS`.


> Yep, it is a bug I from my point of view it will be much better to have the same type regardless backend type or even parameter. And I think if the pattern is string the keys is also should be a string ( of course we can have decode error while we try to make string from bites)

So, what is the final decision? Should I close this pull request and you will update the code to return always strings by default?

**Comment by Krukov** [comment] 2022-05-08 17:42
> I do not understand why do you mention the KEYS Redis command because if you are talking about the cashews.backends.redis.backend._Redis.keys_match defined [here](https://github.com/Krukov/cashews/blob/master/cashews/backends/redis/backend.py#L161), then it uses the [SCAN](https://redis.io/commands/scan/) method, not KEYS.
Oh, my bad, yes it is scan, but in general a few scans without "sleeping" between calls also not good for a big dataset in redis. 

> So, what is the final decision? 
No no, we can discuss it. 
Let me highlight my position. I think that user of library should not think about that parameter - at adds more complexity to understand how to use it in a right way. Also as I sad before he pass a pattern as a string and use a `key` parameter with other methods as a string also - so  it will be more obvious to return string in any cases.
Do you agree with me ?

**Comment by AIGeneratedUsername** [comment] 2022-05-08 18:49
> Let me highlight my position. I think that user of library should not think about that parameter - at adds more complexity to understand how to use it in a right way. Also as I sad before he pass a pattern as a string and use a key parameter with other methods as a string also - so it will be more obvious to return string in any cases.

Yes, I agree.

**Comment by easysugar** [comment] 2022-05-09 16:34
>  it will be more obvious to return string in any cases.
Yope. But I'm affraid it will be a breaking change for some users in case of changing result type of `keys_match` by default. I propose adding other methods for that.

**Comment by Krukov** [comment] 2022-05-09 18:26
@easysugar  good point, yes it should be a new method .

**Comment by Krukov** [comment] 2022-05-09 19:46
@AIGeneratedUsername  Would you like to remake you MR with a new method that fix this issue?

**Comment by AIGeneratedUsername** [comment] 2022-05-09 20:56
>  I'm affraid it will be a breaking change for some users in case of changing result type of keys_match by default.

That is why everybody must pin their requirements. And have a full tests coverage, of course.
We can add a `DeprecationWarning` for the method, and update it on the next major release.

> @AIGeneratedUsername Would you like to remake you MR with a new method that fix this issue?

Do you mean creating a method with a new name? Will this method do the same as `keys_match` for the "Memory" and "Disk" backends, but returns strings for the "Redis" backend? Simplified pseudo-code:
```python
class MemoryBackend:
    keys = keys_match

class DiskBackend:
    keys = keys_match

class RedisBackend:
    async def keys():
           # yield keys as strings...
```

**Comment by Krukov** [comment] 2022-05-10 10:21
@AIGeneratedUsername  Yes right

**Comment by Krukov** [comment] 2022-05-26 19:49
Fixed with a new method `scan`

**Closed by Krukov** 2022-05-26 19:49 UTC
Labels: bug
