### ISSUE TITLE
'coroutine' object has no attribute 'execute_command' - Client Side Caching

### ISSUE THREAD

**Issue by lineup-tk** [Krukov/cashews#158] opened 2023-09-06 14:03 UTC
Environment details:
```
Redis: "7.0"
Redis Python Client: "^4.5.4"
Cashews: "^6.2.0"
CACHE_URL=redis://cache:6379
```

Cashews setup using:
`cache.setup(settings.CACHE_URL, client_side=True, pickle_type="sqlalchemy", middlewares=(logging_middleware,))`

Upon using this setup, the first time an endpoint is called using a @cache decorator, there is an unhandled exception that occurs in:
`File "/code/.venv/lib/python3.10/site-packages/cashews/backends/redis/client_side.py", line 110, in _get_channel`

From a quick investigation it appears that the pubsub method returns a coroutine object that is not being awaited.

This issue does not appear if the cache is setup using client_side=False.

**Comment by Krukov** [comment] 2023-09-17 19:38
Hi @lineup-tk  thanks for reporting this issue. 

Unfortunately I can't reproduce this issue, please provide more information about your env - output of  `pip freeze` and `python -V`

**Comment by Krukov** [comment] 2023-10-15 08:52
I closed this issue, fill free to reopen it with more details about your env

**Closed by Krukov** 2023-10-15 08:52 UTC
